### ISSUE TITLE
NoSuchMethodError stacktraces in server log

### ISSUE THREAD

**Issue by marcelschoen** [ExplosiveMine/Anvil-Revamp#1]
I installed the plugin on Paper 1.19.2, and while it seems to work (haven't properly tested all aspects though), I see lots of these exception stacktraces in the error log:

```
[18:16:44 ERROR]: Could not pass event InventoryCloseEvent to Anvil v1.3.2
java.lang.NoSuchMethodError: 'net.minecraft.world.entity.player.PlayerAbilities net.minecraft.server.level.EntityPlayer.fC()'
	at io.github.explosivemine.anvil.version.Wrapper1_19_R1.setInstaBuild(Wrapper1_19_R1.java:27) ~[Anvil.jar:?]
	at io.github.explosivemine.anvil.menu.MenuListener.onClose(MenuListener.java:44) ~[Anvil.jar:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor1123.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:75) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:git-Paper-211]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:670) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_19_R1.event.CraftEventFactory.handleInventoryCloseEvent(CraftEventFactory.java:1534) ~[paper-1.19.2.jar:git-Paper-211]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.handleContainerClose(ServerGamePacketListenerImpl.java:3069) ~[?:?]
	at org.bukkit.craftbukkit.v1_19_R1.event.CraftEventFactory.callInventoryOpenEvent(CraftEventFactory.java:1348) ~[paper-1.19.2.jar:git-Paper-211]
	at net.minecraft.server.level.ServerPlayer.openMenu(ServerPlayer.java:1517) ~[?:?]
	at net.minecraft.world.level.block.AnvilBlock.use(AnvilBlock.java:60) ~[?:?]
	at net.minecraft.world.level.block.state.BlockBehaviour$BlockStateBase.use(BlockBehaviour.java:1034) ~[?:?]
	at net.minecraft.server.level.ServerPlayerGameMode.useItemOn(ServerPlayerGameMode.java:570) ~[?:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.handleUseItemOn(ServerGamePacketListenerImpl.java:1969) ~[?:?]
	at net.minecraft.network.protocol.game.ServerboundUseItemOnPacket.handle(ServerboundUseItemOnPacket.java:37) ~[?:?]
	at net.minecraft.network.protocol.game.ServerboundUseItemOnPacket.a(ServerboundUseItemOnPacket.java:9) ~[?:?]
	at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$1(PacketUtils.java:51) ~[?:?]
	at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.19.2.jar:git-Paper-211]
	at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
	at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1341) ~[paper-1.19.2.jar:git-Paper-211]
	at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:185) ~[paper-1.19.2.jar:git-Paper-211]
	at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
	at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1318) ~[paper-1.19.2.jar:git-Paper-211]
	at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1311) ~[paper-1.19.2.jar:git-Paper-211]
	at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
	at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1289) ~[paper-1.19.2.jar:git-Paper-211]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1177) ~[paper-1.19.2.jar:git-Paper-211]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:305) ~[paper-1.19.2.jar:git-Paper-211]
	at java.lang.Thread.run(Unknown Source) ~[?:?]
```

**Comment by ExplosiveMine** [comment]
Should be fixed download v1.3.3

**Comment by marcelschoen** [comment]
Thanks, will do. I'll get back to you when I have tried it.

**Comment by ExplosiveMine** [comment]
Have you got around to testing it? I'll close the issue in a few days

**Comment by mschoenUsp** [comment]
Sorry, was too busy and forgot to test it. I'll try to do it today and give you feedback.

**Comment by marcelschoen** [comment]
Tested it now, it's all fine. No exceptions anymore! Thanks!
