### ISSUE TITLE
[BUG] Could not pass event PlayerInteractEvent to Anvil v1.4.10

### ISSUE THREAD

**Issue by makegodhere** [ExplosiveMine/Anvil-Revamp#11]
paper 1.21.3
anvil not opening

```
[16:17:09 ERROR]: Could not pass event PlayerInteractEvent to Anvil v1.4.10
java.lang.NoClassDefFoundError: org/bukkit/craftbukkit/v1_21_R1/entity/CraftPlayer
        at anvil-1.4.10.jar/io.github.explosivemine.anvil.version.Wrapper1_21_R1.getServerPlayer(Wrapper1_21_R1.java:35) ~[anvil-1.4.10.jar:?]
        at anvil-1.4.10.jar/io.github.explosivemine.anvil.version.Wrapper1_21_R1.openInventory(Wrapper1_21_R1.java:18) ~[anvil-1.4.10.jar:?]
        at anvil-1.4.10.jar/io.github.explosivemine.anvil.menu.type.anvil.AnvilMenu.createInv(AnvilMenu.java:27) ~[anvil-1.4.10.jar:?]
        at anvil-1.4.10.jar/io.github.explosivemine.anvil.menu.type.Menu.build(Menu.java:96) ~[anvil-1.4.10.jar:?]
        at anvil-1.4.10.jar/io.github.explosivemine.anvil.menu.type.anvil.AnvilMenu.open(AnvilMenu.java:48) ~[anvil-1.4.10.jar:?]
        at anvil-1.4.10.jar/io.github.explosivemine.anvil.menu.MenuManager.open(MenuManager.java:51) ~[anvil-1.4.10.jar:?]
        at anvil-1.4.10.jar/io.github.explosivemine.anvil.AnvilManager.openAnvil(AnvilManager.java:31) ~[anvil-1.4.10.jar:?]
        at anvil-1.4.10.jar/io.github.explosivemine.anvil.AnvilManager.openAnvil(AnvilManager.java:24) ~[anvil-1.4.10.jar:?]
        at anvil-1.4.10.jar/io.github.explosivemine.anvil.listeners.PlayerEvents.onPlayerInteract(PlayerEvents.java:42) ~[anvil-1.4.10.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor1346.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[paper-api-1.21.3-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[paper-api-1.21.3-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.21.3-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[paper-1.21.3.jar:1.21.3-81-da71382]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:131) ~[paper-1.21.3.jar:1.21.3-81-da71382]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:628) ~[paper-api-1.21.3-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:603) ~[paper-1.21.3.jar:1.21.3-81-da71382]
        at net.minecraft.server.level.ServerPlayerGameMode.useItemOn(ServerPlayerGameMode.java:542) ~[paper-1.21.3.jar:1.21.3-81-da71382]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleUseItemOn(ServerGamePacketListenerImpl.java:1957) ~[paper-1.21.3.jar:1.21.3-81-da71382]
        at net.minecraft.network.protocol.game.ServerboundUseItemOnPacket.handle(ServerboundUseItemOnPacket.java:44) ~[paper-1.21.3.jar:1.21.3-81-da71382]
        at net.minecraft.network.protocol.game.ServerboundUseItemOnPacket.handle(ServerboundUseItemOnPacket.java:11) ~[paper-1.21.3.jar:1.21.3-81-da71382]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:55) ~[paper-1.21.3.jar:1.21.3-81-da71382]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.21.3.jar:1.21.3-81-da71382]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:154) ~[paper-1.21.3.jar:1.21.3-81-da71382]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[paper-1.21.3.jar:1.21.3-81-da71382]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1578) ~[paper-1.21.3.jar:1.21.3-81-da71382]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:207) ~[paper-1.21.3.jar:1.21.3-81-da71382]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:128) ~[paper-1.21.3.jar:1.21.3-81-da71382]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1555) ~[paper-1.21.3.jar:1.21.3-81-da71382]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1548) ~[paper-1.21.3.jar:1.21.3-81-da71382]
        at net.minecraft.util.thread.BlockableEventLoop.runAllTasks(BlockableEventLoop.java:117) ~[paper-1.21.3.jar:1.21.3-81-da71382]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1698) ~[paper-1.21.3.jar:1.21.3-81-da71382]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1330) ~[paper-1.21.3.jar:1.21.3-81-da71382]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:340) ~[paper-1.21.3.jar:1.21.3-81-da71382]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
Caused by: java.lang.ClassNotFoundException: org.bukkit.craftbukkit.v1_21_R1.entity.CraftPlayer
        ... 35 more
```

**Comment by robtherobz** [comment]
bump

**Comment by ExplosiveMine** [comment]
now fixed in latest release. my apologies for extremely late support
