### ISSUE TITLE
1.20 Support?

### ISSUE THREAD

**Issue by Her0-GitHub** [ExplosiveMine/Anvil-Revamp#5]
### When will it be possible for this plugin to work for 1.20?

1.20 Error message when I do command /anvil
``` 
[11:35:45 ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'anvil' in plugin Anvil v1.4.0
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[purpur-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:168) ~[purpur-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_20_R1.CraftServer.dispatchCommand(CraftServer.java:1020) ~[purpur-1.20.1.jar:git-Purpur-2023]
        at org.bukkit.craftbukkit.v1_20_R1.command.BukkitCommandWrapper.run(BukkitCommandWrapper.java:64) ~[purpur-1.20.1.jar:git-Purpur-2023]
        at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:265) ~[purpur-1.20.1.jar:?]
        at net.minecraft.commands.Commands.performCommand(Commands.java:332) ~[?:?]
        at net.minecraft.commands.Commands.performCommand(Commands.java:316) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.performChatCommand(ServerGamePacketListenerImpl.java:2392) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.lambda$handleChatCommand$21(ServerGamePacketListenerImpl.java:2352) ~[?:?]
        at net.minecraft.util.thread.BlockableEventLoop.lambda$submitAsync$0(BlockableEventLoop.java:59) ~[?:?]
        at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) ~[?:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[purpur-1.20.1.jar:git-Purpur-2023]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1366) ~[purpur-1.20.1.jar:git-Purpur-2023]
        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:197) ~[purpur-1.20.1.jar:git-Purpur-2023]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1343) ~[purpur-1.20.1.jar:git-Purpur-2023]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1336) ~[purpur-1.20.1.jar:git-Purpur-2023]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1314) ~[purpur-1.20.1.jar:git-Purpur-2023]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1202) ~[purpur-1.20.1.jar:git-Purpur-2023]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:323) ~[purpur-1.20.1.jar:git-Purpur-2023]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.IllegalStateException: Failed to instantiate version wrapper for version 1.20.1-R0.1-SNAPSHOT
        at io.github.explosivemine.anvil.menu.type.anvil.VersionMatcher.match(VersionMatcher.java:30) ~[Anvil.jar:?]
        at io.github.explosivemine.anvil.menu.type.anvil.AnvilMenu.createInv(AnvilMenu.java:21) ~[Anvil.jar:?]
        at io.github.explosivemine.anvil.menu.type.Menu.build(Menu.java:87) ~[Anvil.jar:?]
        at io.github.explosivemine.anvil.menu.type.anvil.AnvilMenu.open(AnvilMenu.java:41) ~[Anvil.jar:?]
        at io.github.explosivemine.anvil.menu.MenuManager.open(MenuManager.java:49) ~[Anvil.jar:?]
        at io.github.explosivemine.anvil.AnvilPlugin.onCommand(AnvilPlugin.java:62) ~[Anvil.jar:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[purpur-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        ... 23 more
Caused by: java.lang.ClassNotFoundException: io.github.explosivemine.anvil.version.null
        at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:185) ~[purpur-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:152) ~[purpur-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:525) ~[?:?]
        at java.lang.Class.forName0(Native Method) ~[?:?]
        at java.lang.Class.forName(Class.java:375) ~[?:?]
        at io.github.explosivemine.anvil.menu.type.anvil.VersionMatcher.match(VersionMatcher.java:26) ~[Anvil.jar:?]
        at io.github.explosivemine.anvil.menu.type.anvil.AnvilMenu.createInv(AnvilMenu.java:21) ~[Anvil.jar:?]
        at io.github.explosivemine.anvil.menu.type.Menu.build(Menu.java:87) ~[Anvil.jar:?]
        at io.github.explosivemine.anvil.menu.type.anvil.AnvilMenu.open(AnvilMenu.java:41) ~[Anvil.jar:?]
        at io.github.explosivemine.anvil.menu.MenuManager.open(MenuManager.java:49) ~[Anvil.jar:?]
        at io.github.explosivemine.anvil.AnvilPlugin.onCommand(AnvilPlugin.java:62) ~[Anvil.jar:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[purpur-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        ... 23 more
``` 

**Server**
 - OS: [Linux]
 - Type: [purpur]
 - Version [1.20.1]

**Comment by ExplosiveMine** [comment]
Hello, I would be obliged if you would try this pre-release I've just made and let me know if its working correctly. I will then update it on spigot.

[Pre-release link](https://github.com/ExplosiveMine/Anvil-Revamp/releases/tag/1.4.2-beta.1)
Please ignore the source code, I have not pushed out the commits yet.

[Direct download link](https://github.com/ExplosiveMine/Anvil-Revamp/releases/download/1.4.2-beta.1/anvil-1.4.2-beta.1.jar)

**Comment by Her0-GitHub** [comment]
Thanks for replying, sorry I didn't think this pre-release was more up to date than the download from spigot site, for now it seems to run perfectly in 1.20 without any kind of bugs.

**Comment by ExplosiveMine** [comment]
I made the pre-release bexause you opened the issue, it wasn't there before 🤣
